version = 0.1

[default.deploy.parameters]
stack_name = "Lambda-Stack"
resolve_s3 = true
s3_prefix = "Lambda-Stack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

